name: My First GitHub Actions

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: ['3.8.18', '3.9.18']

    steps:
      - uses: actions/checkout@v4

      - name: Setup pyenv
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          pyenv global ${{ matrix.python-version }}
          pyenv rehash
          python --version
          which python

      - name: Install dependencies
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          pyenv global ${{ matrix.python-version }}
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Run tests
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          pyenv global ${{ matrix.python-version }}
          cd src
          python -m pytest -v addition.py
